### ISSUE TITLE
No interaction with application icon even though I have a pointer click

### ISSUE THREAD

**Issue by tanguybernard** [Nanocloud/community#541]
When I try to click on application icon, nothing happens. Even though I have a pointer click.

**Comment by domrod** [comment]
Thanks for your feedback Tanguy.

The current behavior is to click on the application name  to launch the application.

But I understand your point since the icon is shown as also clickable. We should improve that.

Could you by the way precise the Community version you tested?

Thanks for your involvement in Nanocloud Community.

**Comment by tanguybernard** [comment]
Okay, thanks.

Yes: 0.6.0rc1
